### ISSUE TITLE
Support Tracker

### ISSUE THREAD

**Issue by wesleymccollam** [pingidentity/terraform-provider-pingfederate#52]
### Deprecated 3rd Party Provider Coverage (Future Support After MVP)
- [x] Authentication API - Applications Resource
- [x] Authentication Policies - Fragments Resource
- [x] Authentication Policies - Policy Resource
- [x] Authentication Policies - Settings Resource
- [x] Authentication Selectors Resource
- [x] Authentication Session Policy Resource
- [x] Extended Properties Resource
- [x] Idp - Token Processors Resource
- [x] Incoming Proxy Settings Resource
- [x] Kerberos - Realms Resource
- [x] Key Pairs - OpenIDConnect Resource
- [x] Key Pairs - Signing - Generate Resource
- [x] Metadata URLs Resource
- [x] Notification Publishers - Settings Resource
- [x] OAuth - Access Token Mappings Resource
- [x] OAuth - Client Settings Resource 
- [x] OAuth - OpenIDConnect Policies Resource
- [x] OAuth - Resource Owner Credentials Mappings Resource
- [x] PingOneConnections Resource
- [x] SP - Adapters Resource
- [x] SP - Authentication Policy Contract Mappings Resource
- [x] SP - Idp Connections Resource

### MVP => [Released](https://registry.terraform.io/providers/pingidentity/pingfederate/0.4.0)
- [x] Data Stores Resource
- [x] Idp - Adapters Resource 
- [x] Idp - SP Connections Resource
- [x] OAuth - Clients Resource
- [x] OAuth - OpenIDConnect - Policies Resource
- [x] OAuth - Token Exchange - Token Generator Mappings Resource
- [x] SP - Authentication Policy Contract Mappings Resource
- [x] Token Processor to Token Generator Mappings Resource
- [x] Data Source Types for all applicable resource types from EA and MVP

### EA => [Released](https://registry.terraform.io/providers/pingidentity/pingfederate/0.1.0)
- [x] Administrative Accounts Resource
- [x] Authentication API - Settings Resource
- [x] Authentication Policy Contracts Resource
- [x] Certificates - CA Import Resource
- [x] Idp - Default URLs Resource
- [x] Key Pairs - Signing - Import Resource
- [x] Key Pairs - SSL Server Resource
- [x] License Resource
- [x] License Agreement Resource
- [x] Local Identity Identity Profiles Resource
- [x] OAuth - Access Token Managers Resource
- [x] OAuth - Auth Server Settings Resource
- [x] OAuth - Auth Server Settings - Common Scopes Resource
- [x] OAuth - Auth Server Settings - Exclusive Scopes Resource
- [x] OAuth - Issuers Resource
- [x] Password Credential Validators Resource
- [x] Protocol Metadata - Lifetime Settings Resource
- [x] Redirection Validation Resource
- [x] Server Settings Resource
- [x] Server Settings - General Settings Resource
- [x] Server Settings - Log Settings Resource
- [x] Server Settings - System Keys Resource
- [x] Session - Application Session Policy Session
- [x] Session - Authentication Session Policies - Global Resource
- [x] Session - Settings Resource
- [x] Virtual Host Names Resource

#### Disclaimers: 
- There will be periodical releases for new resources and data sources, as well as ones not currently listed for future development
- Future resources and data sources may not be implemented if the resource is not Terraform-friendly. A type could be listed that may not be supported.
